### ISSUE TITLE
[PLUGIN REQUEST] Strapi Plugin: Graphs Builder

### ISSUE THREAD

**Issue by surgeharb** [Stun3R/isstrapiready#25]
### Name

strapi-plugin-graphs-builder

### Link

https://github.com/surgeharb/strapi-plugin-graphs-builder

### Status

Ready

### Author

@surgeharb

**Comment by Stun3R** [comment]
I just added to the list! As your plugin is ready to use, I close the issue :) Thanks again for this request ❤️
