### ISSUE TITLE
[PLUGIN/PROVIDER REQUEST] strapi-plugin-comments

### ISSUE THREAD

**Issue by ZDVokoun** [Stun3R/isstrapiready#34]
### Name

strapi-plugin-comments

### Link

https://github.com/VirtusLab-Open-Source/strapi-plugin-comments

### Status

Work In Progess

### Type

Plugin

**Comment by ZDVokoun** [comment]
More info here: https://github.com/VirtusLab-Open-Source/strapi-plugin-comments/discussions/92

**Comment by cyp3rius** [comment]
@Stun3R, plugin got `rc.1` version already so it might be marked as `Ready` :)
