### ISSUE TITLE
Several official @strapi Plugins are missing

### ISSUE THREAD

**Issue by tilman** [Stun3R/isstrapiready#40]
A complete list of them can be found here: https://github.com/strapi/awesome-strapi#strapi-v4
Would be nice if you can add these as well. For example this one is missing: https://github.com/strapi/strapi/tree/master/packages/providers/upload-aws-s3

**Comment by Stun3R** [comment]
We are aware that official providers are missing in the list ☺️ We will add them as soon as possible 👌🏻
