### ISSUE TITLE
[PLUGIN REQUEST] Comments plugin - Beta with v4 support

### ISSUE THREAD

**Issue by cyp3rius** [Stun3R/isstrapiready#44]
### Name

strapi-plugin-comments

### Link

https://www.npmjs.com/package/strapi-plugin-comments

### Status

Work In Progress (Beta released)

### Type

Plugin

### Author

https://github.com/VirtusLab-Open-Source

**Comment by Stun3R** [comment]
Close since it's duplication of #34
