### ISSUE TITLE
Documentation says 100%, even though 2 of 3 migration guides are missing

### ISSUE THREAD

**Issue by sabberworm** [Stun3R/isstrapiready#51]
IMHO documentation cannot be considered complete without migration guides.

See [migration guide info box](https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html), which currently says code and data migration guides are coming in March 2022.

<img width="927" alt="image" src="https://user-images.githubusercontent.com/47652/151234295-1d160403-8818-40b0-81d9-7e86880af0a1.png">

**Comment by Stun3R** [comment]
You are right, I will change it
